### ISSUE TITLE
这个项目只能一次运行一整个数据集吗？能不能为几张图片做验证呢

### ISSUE THREAD

**Issue by s0mexx** [weiqingq/CLRKDNet#1]

**Comment by weiqingq** [comment]
We only support

**Comment by weiqingq** [comment]
目前的dataloader只支持整个数据集输入，对CuLane数据集可以通过修改或重写test.txt文件来指定图片
https://github.com/weiqingq/CLRKDNet/blob/f288b6d0facd9375a823eef8722e06f6a9628921/clrkd/datasets/culane.py#L15

**Comment by weiqingq** [comment]
对新图片推理可以参考以下代码
https://github.com/Turoad/lanedet/blob/main/tools/detect.py

**Comment by s0mexx** [comment]
请问你本地有测试代码吗，有运行的结果可以发给我吗写一下大作业吧 实在跑不通

**Comment by weiqingq** [comment]
稍等下, 我上传百度网盘, 等下发你链接

**Comment by s0mexx** [comment]
非常非常非常感谢🥹我真的太着急了，希望没有打扰到你

**Comment by weiqingq** [comment]
https://pan.baidu.com/s/1dA37bVIw47Z2rUGZ6_dHvg?pwd=aqgx
这是用ResNet18 Backbone的运行结果, 包含全部的Culane测试集, 可视化结果在visualization文件夹里

**Comment by weiqingq** [comment]
希望对你有帮助
