### ISSUE TITLE
各位注意，未开源！未开源！

### ISSUE THREAD

**Issue by 605789414** [weiqingq/CLRKDNet#4]
未开源！

**Comment by AWJ0925** [comment]
找不到蒸馏的代码！！！

**Comment by happy-q123** [comment]
> 找不到蒸馏的代码！！！

感谢

**Comment by utkutpcgl** [comment]
Thanks!

**Comment by weiqingq** [comment]
Apologies for the delayed response. I have been occupied with other projects. However, the official training code is now available.
